### ISSUE TITLE
Could not load file or assembly error on .NET Framework

### ISSUE THREAD

**Issue by george-tifrea** [waxtell/Serilog.Sanitizer#10]
**Describe the bug**
It seems that the latest version (preview version) is not working anymore in .NET Framework 4.7.2.
The strong named preview seemed to be working last year, in May, when we tested it, but we waited for a official release to add it to our projects.

**To Reproduce**
1. Create new ASP.NET web application (from VS sample)
2. Add the Serilog.Sanitizer package 1.3.1 (or alpha)
3. Run the application from VS (or publish in IIS)
4. Access the application.
5. The following stack trace will appear:

[FileLoadException: Could not load file or assembly 'Serilog.Sanitizer' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)]

[FileLoadException: Could not load file or assembly 'Serilog.Sanitizer, Version=1.3.1.0, Culture=neutral, PublicKeyToken=ea6723327de9b476' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)]
   System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +0
   System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +232
   System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection) +113
   System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection) +23
   System.Reflection.Assembly.Load(String assemblyString) +35
   System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +49

[ConfigurationErrorsException: Could not load file or assembly 'Serilog.Sanitizer, Version=1.3.1.0, Culture=neutral, PublicKeyToken=ea6723327de9b476' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)]
   System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +762
   System.Web.Configuration.CompilationSection.LoadAllAssembliesFromAppDomainBinDirectory() +259
   System.Web.Configuration.CompilationSection.LoadAssembly(AssemblyInfo ai) +167
   System.Web.Compilation.BuildManager.GetReferencedAssemblies(CompilationSection compConfig) +238
   System.Web.Compilation.BuildManager.GetPreStartInitMethodsFromReferencedAssemblies() +78
   System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean& isRefAssemblyLoaded) +334
   System.Web.Compilation.BuildManager.ExecutePreAppStart() +178
   System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +746

[HttpException (0x80004005): Could not load file or assembly 'Serilog.Sanitizer, Version=1.3.1.0, Culture=neutral, PublicKeyToken=ea6723327de9b476' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +552
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +122
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +737

**Expected behavior**
There is no error on assembly loading

**Screenshots**
![image](https://user-images.githubusercontent.com/26331832/152488610-8ddd1e34-4e5f-444b-9d91-4e8e8f573146.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 1.3.1

**Additional context**
Our .NET Core / NET 6 apps seems to work properly, however our ASP.NET APIs raise the above error when accessed

**Comment by waxtell** [comment]
Investigating...

Great write-up, btw!

**Comment by waxtell** [comment]
I was able to reproduce the error.  Interestingly, the inclusion of net5.0 in the framework targets does not play nice with 4.7.2.  Please try 1.3.2-beta which does not include the net5.0 target.

**Comment by waxtell** [comment]
Release package published.

**Comment by caappa** [comment]
Hi,
I updated to 1.3.2 (I also used the 1.3.2.beta) and the problem still reproduce, I am still getting
![image](https://user-images.githubusercontent.com/13849454/156330787-11f37437-3634-422e-bc7c-2fe981a55c1f.png)

It is the original project from the thread added by george-tifrea, where we have .net framwork 2.7.2 - wcf service and we have also .net 6 (.net core) - Windows Services,

**Comment by waxtell** [comment]
Any better with 1.3.3-alpha?
