### ISSUE TITLE
Provide assembly with strong name

### ISSUE THREAD

**Issue by nicoleta-scrimint** [waxtell/Serilog.Sanitizer#4]
We have an internal rule in the company that all our assemblies need to have strong names.

When using the assembly "Serilog.Sanitizer.dll" from this nuget package, we have an issue in a .Net Framework project that the referenced assembly is not strong named.

According to [this article](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming#:~:text=Strong%20naming%20refers%20to%20signing,can%20help%20prevent%20assembly%20conflicts.&text=When%20.), this issue does not occur in .Net Core projects and occurs only in .Net Framework projects due to strict assembly loading.

I would like to ask you if you could provide an assembly with a strong name for this nuget package so that also .net framework projects which require a strong name key to use this nuget package?

Thank you!

**Comment by waxtell** [comment]
I will try and find some time soon to update the package.  Thanks for the feedback!

**Comment by nicoleta-scrimint** [comment]
Hi!
Any new updates on this matter?
Thank you!

**Comment by waxtell** [comment]
[1.3.1-alpha](https://www.nuget.org/packages/Serilog.Sanitizer/1.3.1-alpha) is available to test.  Would love your feedback...

**Comment by nicoleta-scrimint** [comment]
We will test the package and let you know upon the result.
Thank you!

**Comment by george-tifrea** [comment]
I have tested it for a bit and, for our use cases, no issues appeared. The strong naming was also working as expected.

**Comment by nicoleta-scrimint** [comment]
Could you please make an official NuGet version with the strong sign changes?
Thank you!

**Comment by waxtell** [comment]
Done!  Stay safe and have a wonderful holiday season!
